name: Future Crunch
favicon: null
layout_spectrum: 0.19117
typography_spectrum: 0.16011
title: Future Crunch
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#323232'
    - '#07c6df'
    - '#a98c33'
    - '#0d6279'
  brandStrength: 1
  lightness: 0
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
