name: Future Crunch
favicon: null
layout_spectrum: 1
typography_spectrum: 0.8778752284124494
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000d28'
    - '#194079'
    - '#3377b6'
    - '#599dce'
    - '#8bc5eb'
  brandStrength: 0.5625
  lightness: 0.875
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose: []
