name: Future Crunch
favicon: null
layout_spectrum: 0.80162
typography_spectrum: 0.50637
title: Future Crunch
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#d1c4a1'
    - '#aea27c'
    - '#877a57'
    - '#ede7ca'
  brandStrength: 0.625
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 1
purpose: []
